spring:
  datasource:
    url: ${MYCHART_DB_URL:jdbc:mysql://localhost:3306/mychart?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${MYCHART_DB_USERNAME:mychart_user}
    password: ${MYCHART_DB_PASSWORD:mychart_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
