spring:
  datasource:
    url: ${MYCHART_DB_URL}
    username: ${MYCHART_DB_USERNAME}
    password: ${MYCHART_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

logging:
  level:
    root: INFO
    com.MyChart: INFO
